// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="pt-20 bg-gray-50 min-h-screen">{children}</body>
//     </html>
//   );
// }




import './globals.css'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'Artistly',
  description: 'Book artists for your events',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pt-20 bg-gray-50 min-h-screen">
        <Navbar />
        <main className="max-w-7xl mx-auto px-4">{children}</main>
      </body>
    </html>
  )
}
